### ISSUE TITLE
how can i see the top down map

### ISSUE THREAD

**Issue by GELIELEO** [jkulhanek/visual-navigation-agent-pytorch#1]
how can i see the top down map?

**Comment by jkulhanek** [comment]
You can use the H5 scene dump provided by the authors of the paper.

**Comment by GELIELEO** [comment]
any tool recommend?

**Comment by jkulhanek** [comment]
Look at the documentation of the H5PY package. Then, Seaborn is a great tool for visualizing the grid https://seaborn.pydata.org/generated/seaborn.heatmap.html. I used it when visualizing the map and the trained policy and value function.
